// Regenerates src/social-image-palettes.generated.ts from Design Kit's
// palette-system.css. The social card cannot import the CSS (the pinned
// runtime Design Kit release predates it and cards read no files at run
// time), so a reviewed copy lives in fixtures/design-kit and a test pins the
// generated table to it.
//
//   bun run ./scripts/sync-design-kit-palettes.ts <design-kit tag> [palette-system.css]
//
// With only a tag, the CSS is read from that tag of hraness/design-kit
// through the GitHub CLI. Commit the refreshed fixture and table together.
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

import { parseDesignKitLightPalettes } from "../src/social-image-palette-css.js";

const root = resolve(import.meta.dir, "..");
const [tagArgument, cssPath] = process.argv.slice(2);
if (tagArgument === undefined || !/^v\d+\.\d+\.\d+$/u.test(tagArgument)) {
  throw new Error("usage: sync-design-kit-palettes.ts <vX.Y.Z> [palette-system.css]");
}
const tag: string = tagArgument;

async function upstream(): Promise<string> {
  if (cssPath !== undefined) return readFile(cssPath, "utf8");
  const process_ = Bun.spawnSync(["gh", "api", "-H", "Accept: application/vnd.github.raw", `repos/hraness/design-kit/contents/src/palette-system.css?ref=${tag}`]);
  if (process_.exitCode !== 0) throw new Error(process_.stderr.toString());
  return process_.stdout.toString();
}

const css = await upstream();
const palettes = parseDesignKitLightPalettes(css);
const digest = createHash("sha256").update(css).digest("hex");
await writeFile(join(root, "fixtures/design-kit/palette-system.css"), css);

const body = Object.entries(palettes)
  .map(([name, colors]) => `  ${JSON.stringify(name)}: ${JSON.stringify(colors).replace(/"(\w+)":/gu, "$1: ").replace(/,/gu, ", ").replace(/^\{/u, "{ ").replace(/\}$/u, " }")},`)
  .join("\n");
await writeFile(join(root, "src/social-image-palettes.generated.ts"), `// Generated by scripts/sync-design-kit-palettes.ts. Do not edit.
// Source: hraness/design-kit ${tag} src/palette-system.css (light theme),
// copied to fixtures/design-kit/palette-system.css.

export const DESIGN_KIT_PALETTE_SOURCE = {
  path: "src/palette-system.css",
  sha256: "${digest}",
  tag: "${tag}",
} as const;

export const DESIGN_KIT_LIGHT_PALETTES = {
${body}
} as const;
`);
console.log(`wrote ${String(Object.keys(palettes).length)} palettes from design-kit ${tag}`);
