// Generated by scripts/sync-design-kit-palettes.ts. Do not edit.
// Source: hraness/design-kit v0.32.0 src/palette-system.css (light theme),
// copied to fixtures/design-kit/palette-system.css.

export const DESIGN_KIT_PALETTE_SOURCE = {
  path: "src/palette-system.css",
  sha256: "1037d208f7a2745fbe3667457c8b69e7ec5b1bd6f5a6ffd588072459411a8ba6",
  tag: "v0.32.0",
} as const;

export const DESIGN_KIT_LIGHT_PALETTES = {
  "catppuccin": { background: "#eff1f5", foreground: "#3a3c50", muted: "#545768", line: "#ccd0da", surface: "#e6e9ef", primary: "#1750bf" },
  "gruvbox": { background: "#fbf1c7", foreground: "#393533", muted: "#584f48", line: "#d5c4a1", surface: "#f9f5d7", primary: "#065968" },
  "rose-pine": { background: "#faf4ed", foreground: "#44405e", muted: "#605c74", line: "#dfdad9", surface: "#fffaf3", primary: "#68587a" },
  "tokyo-night": { background: "#e1e2e7", foreground: "#1c3161", muted: "#414c76", line: "#b7c1e3", surface: "#d0d5e3", primary: "#1d4e90" },
  "paper": { background: "#f8f7f4", foreground: "#1c1917", muted: "#6c665f", line: "#b9b3ab", surface: "#fffefa", primary: "#1e5ae1" },
} as const;
